declare var __DEV__: boolean
declare var __PROD__: boolean
declare var __VERSION__: string
declare namespace NodeJS {
    interface ProcessEnv {
        SHELL:string
        SESSION_MANAGER:string
        COLORTERM:string
        XDG_CONFIG_DIRS:string
        XDG_SESSION_PATH:string
        COREPACK_ENABLE_DOWNLOAD_PROMPT:string
        NVM_INC:string
        XDG_MENU_PREFIX:string
        TERM_PROGRAM_VERSION:string
        ICEAUTHORITY:string
        NODE_OPTIONS:string
        LC_ADDRESS:string
        LC_NAME:string
        MEMORY_PRESSURE_WRITE:string
        DESKTOP_SESSION:string
        LC_MONETARY:string
        GTK_RC_FILES:string
        NO_AT_BRIDGE:string
        EDITOR:string
        XDG_SEAT:string
        PWD:string
        LOGNAME:string
        XDG_SESSION_DESKTOP:string
        XDG_SESSION_TYPE:string
        SYSTEMD_EXEC_PID:string
        _:string
        XAUTHORITY:string
        VSCODE_GIT_ASKPASS_NODE:string
        MOTD_SHOWN:string
        GTK2_RC_FILES:string
        HOME:string
        COREPACK_ROOT:string
        LANG:string
        LC_PAPER:string
        XDG_CURRENT_DESKTOP:string
        npm_package_version:string
        MEMORY_PRESSURE_WATCH:string
        STARSHIP_SHELL:string
        WAYLAND_DISPLAY:string
        GIT_ASKPASS:string
        XDG_SEAT_PATH:string
        INVOCATION_ID:string
        MANAGERPID:string
        INIT_CWD:string
        CHROME_DESKTOP:string
        STARSHIP_SESSION_KEY:string
        KDE_SESSION_UID:string
        NVM_DIR:string
        VSCODE_GIT_ASKPASS_EXTRA_ARGS:string
        XKB_DEFAULT_LAYOUT:string
        XDG_ACTIVATION_TOKEN:string
        XDG_SESSION_CLASS:string
        LC_IDENTIFICATION:string
        TERM:string
        npm_package_name:string
        PROJECT_CWD:string
        USER:string
        VSCODE_GIT_IPC_HANDLE:string
        QT_WAYLAND_RECONNECT:string
        KDE_SESSION_VERSION:string
        PAM_KWALLET5_LOGIN:string
        DISPLAY:string
        npm_lifecycle_event:string
        SHLVL:string
        NVM_CD_FLAGS:string
        LC_TELEPHONE:string
        LC_MEASUREMENT:string
        XDG_VTNR:string
        XDG_SESSION_ID:string
        npm_config_user_agent:string
        npm_execpath:string
        XDG_RUNTIME_DIR:string
        DEBUGINFOD_URLS:string
        npm_package_json:string
        LC_TIME:string
        BUN_INSTALL:string
        BERRY_BIN_FOLDER:string
        XKB_DEFAULT_VARIANT:string
        VSCODE_GIT_ASKPASS_MAIN:string
        QT_AUTO_SCREEN_SCALE_FACTOR:string
        JOURNAL_STREAM:string
        XDG_DATA_DIRS:string
        KDE_FULL_SESSION:string
        GDK_BACKEND:string
        BROWSER:string
        PATH:string
        ORIGINAL_XDG_CURRENT_DESKTOP:string
        DBUS_SESSION_BUS_ADDRESS:string
        KDE_APPLICATIONS_AS_SCOPE:string
        MAIL:string
        NVM_BIN:string
        npm_node_execpath:string
        LC_NUMERIC:string
        OLDPWD:string
        TERM_PROGRAM:string
        TOKEN:string
        PREFIX:string
        MONGODB:string
        YOURLS_KEY:string
        CATAPI:string
        DOGAPI:string
        TWITTER:string
        MAKESWEET:string
        GENIUS:string
        SPOTIFY_CLIENT:string
        SPOTIFY_SECRET:string
        CF_AI_TOKEN:string
        CF_AI_ACC:string
        GUILDID:string
        SUGGESTIONS_CHANNEL:string
        MODLOGS_CHANNEL:string
        JOINSANDLEAVES_CHANNEL:string
        SOCIALS_CHANNEL:string
        BIRTHDAYS_CHANNEL:string
        MCFORM_CHANNEL:string
        CHATGPT_CHANNEL:string
        T_CHANNEL:string
    }
}
